name: Docker

on:
  push:
    branches:
      - docker-compose
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Docker Compose Up
        run: |
          docker compose -h
          docker compose up -h
