name: Docker

on:
  push:
    branches:
      - "multi-docker-files"
    paths:
      - "docker/**"

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          json: "true"
          dir_names: "true"
          files: docker/**

      - run: echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - id: set-matrix
        run: |
          changes=${{ steps.changed-files.outputs.all_changed_files }}
          change_dirs=$(echo "$changes" | jq -c)
          echo "::set-output name=matrix::$change_dirs"

      - run: |
          echo "${{ steps.set-matrix.outputs.matrix }}"
          echo "${{ toJson(steps.changed-files.outputs) }}"

  build:
    if: needs.matrix.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    needs:
      - matrix
    strategy:
      fail-fast: false
      matrix:
        docker: ${{ fromJson(needs.matrix.outputs.changes) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.docker }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.docker }}-

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker }}
          file: ${{ matrix.docker }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix https://github.com/docker/build-push-action/issues/252 https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
