name: Environment

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo dev >> file
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dev
          path: ${{ github.workspace }}
