name: Environment

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com
    steps:
      - name: Run
        run: echo ${{ env.environment }}
      
