name: Environment

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
    environment:
      name: dev
      url: https://github.com
    steps:
      - name: Run
        run: echo ${ENV}
        env:
          ENV: ${{ env.ENVIRONMENT }}
