name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "username: ${{ inputs.username }}"
          echo "IMAGE_TAG: ${IMAGE_TAG}"
    env:
      IMAGE_TAG: ${{ github.run_id }}.0${{ github.run_number }}
