name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      extra_env:
        required: false
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Extra ENV
        if: inputs.extra_env != null
        run: echo "${{ inputs.extra_env }}" | tr ',' '\n' >> $GITHUB_ENV

      - name: Output ENV
        run: |
          echo "username: ${{ inputs.username }}"
          echo "IMAGE_TAG: ${IMAGE_TAG}"
          echo "GLOBAL_ENV: ${GLOBAL_ENV}"
          export
        env:
          IMAGE_TAG: ${{ github.run_id }}.0${{ github.run_number }}.${{ github.run_attempt }}
