name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      extra_env:
        required: false
        type: string
      matrix:
        required: false
        type: string
        default: matrix
      read_file:
        required: false
        type: string

jobs:
  matrix-prep:
    runs-on: ubuntu-latest
    outputs:
      matrices: ${{ steps.tests.outputs.matrices }}
    steps:
      - id: tests
        run: |
          export matrix=${{ inputs.matrix }}
          echo "matrix: ${matrix}"
          export matrices=$(echo $matrix | jq -R 'split(",") | '.'' | jq -c)
          echo "matrices: ${matrices}"
          echo ::set-output name=matrices::$matrices
      - run: echo ${{ steps.tests.outputs.matrices }}

  example_job:
    runs-on: ubuntu-latest
    needs:
      - matrix-prep
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.matrix-prep.outputs.matrices) }}
    steps:
      - name: Extra ENV
        if: inputs.extra_env != null
        run: echo "${{ inputs.extra_env }}" | tr ',' '\n' >> $GITHUB_ENV

      - name: Output ENV
        run: |
          echo "username: ${{ inputs.username }}"
          echo "IMAGE_TAG: ${IMAGE_TAG}"
          echo "GLOBAL_ENV: ${GLOBAL_ENV}"
          echo "MATRIX: ${{ matrix.environment }}"
          export
        env:
          IMAGE_TAG: ${{ github.run_id }}.0${{ github.run_number }}.${{ github.run_attempt }}

      - name: Read File
        run: |
          echo "\nTest Condition\n" >> ${{ inputs.file != null && inputs.file || 'README.md' }}
          cat ${{ inputs.file != null && inputs.file || 'README.md' }}
