name: Test Release

on:
  push:
    branches:
      - release/*
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone git@github.com:ohcnkk/literate-winner.git
          cd literate-winner
          [[ git checkout ${{ github.ref_name }} || true
          ls -ltr
