name: Test Output

on:
  push:
    branches: 
      - main
      - develop

env:
  GLOBAL_ENV: global_env_test

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "main workflow"
      
  # workspace:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: mkdir newdir && touch newdir/newfile
  #     - run: |
  #         echo "NEW_DIR is $NEW_DIR"
  #         ls -ltr $NEW_DIR
  #         echo $BUILD >> $NEW_DIR/newfile
  #         cat $NEW_DIR/newfile
  #       env:
  #         NEW_DIR: ${{ github.workspace }}/newdir
  #         BUILD: ${{ github.sha }}

  # anotations:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       container: [ foo, bar ]
  #   steps:
  #     - run: echo "::notice::$IMAGE:$TAG"
  #       env:
  #         IMAGE: ${{ matrix.container }}
  #         TAG: latest
          
  # reusable-workflow:
  #   uses: ./.github/workflows/reusable-workflow.yml
  #   with:
  #     username: ${{ github.actor }}
   
  # dump-gh-context:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"

#   fail:
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1

#   windows:
#     runs-on: windows-2019
#     steps:
#       - shell: pwsh
#         run: |
#           Install-Module -Name AWS.Tools.Installer -Force
#           Install-AWSToolsModule AWS.Tools.EC2 -Force
#           $Filter = @{ Name="name"; Values="Windows_Server-2019-English-Full-Base*" }
#           $Ec2Images = Get-EC2Image -Owner '801119661308' -Filter $Filter
#           packer version

  javascript:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/github-script@v6
      #   id: set-result
      #   with:
      #     script: return "Hello!"
      #     result-encoding: string
      # - name: Get result
      #   run: echo "${{steps.set-result.outputs.result}}"
      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const url = 'https://httpbin.org/get'
      #       const result = await github.request(url)
      #       console.log(result)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install @actions/http-client
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/script.js')
            console.log(script())