name: Test Output

on:
  push:
    branches: 
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main workflow"
      
  workspace:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir newdir && touch newdir/newfile
      - run: |
          echo "NEW_DIR is $NEW_DIR"
          ls -ltr $NEW_DIR
          echo $BUILD >> $NEW_DIR/newfile
          cat $NEW_DIR/newfile
        env:
          NEW_DIR: ${{ github.workspace }}/newdir
          BUILD: ${{ github.sha }}

#   fail:
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1
