name: Test Output

on:
  push:
    branches: 
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main workflow"

  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
