name: Test Output

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main workflow"

  example:
    uses: ohcnkk/temp/.github/workflows/reusable-workflow.yml@main
    with:
      username: ohcnkk
