name: Test Release

on:
  push:
    branches:
      - release/*
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ohcnkk/literate-winner
          path: literate-winner

      - run: |
          REPOS_DIR=(literate-winner)
          for DIR in ${REPOS_DIR[@]}; do
            WORK_DIR="${{ github.workspace }}/$DIR"
            cd $WORK_DIR
            git fetch --all
            LATEST_RELEASE=$(git branch --remotes --sort=-committerdate | grep 'release/' | head -n 1 | grep -o 'release.*')
            if [ -z "$LATEST_RELEASE" ]; then
              echo "=== No release branch found for $DIR and using default branch ==="
            else
              echo "=== Using $LATEST_RELEASE branch for $DIR ==="
              git checkout --progress --force -B $LATEST_RELEASE refs/remotes/origin/$LATEST_RELEASE
            fi
          done
