name: Test Release

on:
  push:
    branches:
      - release/*
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ohcnkk/literate-winner
          path: literate-winner

      - run: |
          cd literate-winner
          git fetch --all
          LATEST_RELEASE=$(git branch --remotes --sort=-committerdate | grep 'release/' | head -n 1 | grep -o 'release.*') >&2
          echo $?
          #if [ $? -ne 0 ]; then
          #  echo "No release branch found and using default branch"
          #else
          #  echo "Using $LATEST_RELEASE branch"
          #  git checkout --progress --force -B $LATEST_RELEASE refs/remotes/origin/$LATEST_RELEASE
          #fi
