name: Test Release

on:
  push:
    branches:
      - release/*
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git clone git@github.com:ohcnkk/literate-winner.git
          cd literate-winner
          [[ git checkout ${{ github.ref_name }} ]] && echo "Using Release branch"
          ls -ltr
