name: Workflow Run

on:
  workflow_run:
    workflows: [ Test Output ]
    types: [ completed ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ fromJSON(github.event.workflow_run) }}"
