name: Test Output

on:
  push:
    branches: 
    - 'main'
    - 'release/20[22-99].[0-9]+.[0-9]+'
    - 'hotfix/20[22-99].[0-9]+.[0-9]+_[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main workflow"
      
  workspace:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir newdir && touch newdir/newfile
      - run: |
          echo "NEW_DIR is $NEW_DIR"
          ls -ltr $NEW_DIR
          echo $BUILD >> $NEW_DIR/newfile
          cat $NEW_DIR/newfile
        env:
          NEW_DIR: ${{ github.workspace }}/newdir
          BUILD: ${{ github.sha }}

  anotations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [ foo, bar ]
    steps:
      - run: echo "::notice::$IMAGE:$TAG"
        env:
          IMAGE: ${{ matrix.container }}
          TAG: latest
          
  reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      username: ${{ github.actor }}

  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
