name: Workflow Run

on:
  workflow_run:
    workflows: [ Environment ]
    types: [ completed ]

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.* }}"
      - run: echo "workflow_id ${{ github.event.workflow_run.workflow_id }}"
      - run: echo "github.ref_name is ${{ github.ref_name }}"
      - run: echo "GITHUB_REF_NAME is ${GITHUB_REF_NAME}"

#   sleep:
#     needs: [run]
#     runs-on: ubuntu-latest
#     steps:
#       - run: sleep 10

#   always:
#     needs: [sleep]
#     if: always()
#     continue-on-error: true
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "always step..."

  download:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
    environment:
      name: dev
      url: https://github.com
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: environment.yml
          workflow_conclusion: success
          name: ${{ env.ENVIRONMENT }}
